INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2013',7023);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2014',5384);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2015',6524);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2016',6469);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2013',3454);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2014',2634);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2015',3205);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2016',3161);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2013',3569);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2014',2750);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2015',3319);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2016',3308);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2013',2308);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2014',1828);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2015',2479);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2016',2535);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2013',3279);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2014',2633);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2015',3518);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2016',3734);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2013',41);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2014',38);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2015',36);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2016',45);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2013',4);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2014',3);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2015',4);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','all pure and cross breeds','2016',10);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2013',5158);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2014',3974);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2015',4672);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2016',4631);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2013',2488);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2014',1908);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2015',2258);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2016',2233);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2013',2670);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2014',2066);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2015',2414);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2016',2398);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2013',1477);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2014',1158);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2015',1528);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2016',1542);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2013',2142);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2014',1775);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2015',2279);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2016',2439);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2013',20);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2014',22);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2015',17);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2016',15);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2013',2);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2014',1);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2015',3);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','aa_all (pure)','2016',3);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2013',46);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2014',33);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2015',43);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2016',38);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2013',23);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2014',18);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2015',19);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2016',18);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2013',23);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2014',15);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2015',24);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2016',20);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2013',20);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2014',15);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2015',19);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2016',18);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2013',36);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2014',27);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2015',34);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2016',31);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2013',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2014',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2015',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2016',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2013',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2014',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2015',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Beagle','2016',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2013',161);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2014',123);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2015',133);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2016',142);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2013',82);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2014',59);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2015',70);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2016',73);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2013',79);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2014',64);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2015',63);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2016',69);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2013',59);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2014',54);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2015',70);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2016',76);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2013',109);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2014',85);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2015',98);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2016',111);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2013',1);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2014',1);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2015',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2016',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2013',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2014',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2015',1);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Bichon Frise','2016',1);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2013',54);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2014',43);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2015',53);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2016',54);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2013',24);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2014',18);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2015',26);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2016',29);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2013',30);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2014',25);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2015',27);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2016',25);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2013',25);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2014',18);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2015',26);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2016',31);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2013',39);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2014',31);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2015',41);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2016',42);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2013',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2014',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2015',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2016',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2013',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2014',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2015',0);
INSERT INTO control_statistics(council_name,breed,year,value) VALUES ('Ashburton District','Boxer','2016',0);
